stages:
  - build
  - package

build_job:
  stage: build
  tags:
    - linux
  script:
    - set -xe
    - cd /var/www/dotnetdeploy/RSign.SendAPI/

    - git reset --hard
    - git clean -fd
    - git pull origin main

    - dotnet restore RSign.SendAPI.csproj
    - dotnet build RSign.SendAPI.csproj --configuration Release

package_job:
  stage: package
  tags:
    - linux
  script:
    - cd /var/www/dotnetdeploy
    - dotnet publish RSign.SendAPI.csproj -c Release -o publish
  artifacts:
    paths:
      - publish