//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLog
    {
        public long TransId { get; set; }
        public string? MessageId { get; set; }
        public System.DateTime TimeLogged { get; set; }
        public System.DateTime TimeQueued { get; set; }
        public string? Origin { get; set; }
        public string? Recipient { get; set; }
        public string? DsnStatus { get; set; }
        public string? dsnDiag { get; set; }
        public string? dsnMta { get; set; }
        public string? BounceCategory { get; set; }
        public string? SourceType { get; set; }
        public string? SourceMTAServer { get; set; }
        public string? DeliveryType { get; set; }
        public string? DeliverySourceIP { get; set; }
        public string? DeliveryDestinationIP { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public string? EnvelopeCode { get; set; }
        public string? DsnAction { get; set; }
    }
}
