//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkUploadTransaction
    {
        public long TransID { get; set; }
        public long BulkUploadTransId { get; set; }
        public string? RoleName { get; set; }
        public string? RoleType { get; set; }
        public string? RecipientName { get; set; }
        public string? RecipientEmail { get; set; }
        public string? Comments { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public int TemplateCode { get; set; }
        public string CountryCode { get; set; }
        public string Mobile { get; set; }
        public string DialCode { get; set; }
      //  public Nullable<int> ReminderType { get; set; }

        public virtual BulkUploadTemplate BulkUploadTemplate { get; set; }
    }
}
