//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkUploadTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BulkUploadTemplate()
        {
            this.BulkUploadTransaction = new HashSet<BulkUploadTransaction>();
        }
    
        public long TransId { get; set; }
        public int TemplateCode { get; set; }
        public int Status { get; set; }
        public string? ServerName { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> MessageTemplateCode { get; set; }
        public string? Subject { get; set; }
        public string? Message { get; set; }
        public string? UserToken { get; set; }
        public string? EmailID { get; set; }
        public string? BatchID { get; set; }
        public string? CreatedSource { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulkUploadTransaction> BulkUploadTransaction { get; set; }
    }
}
