//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyAppKeys
    {
        public int Id { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public string? CompanyRefKey { get; set; }
        public string? Appkey { get; set; }
    }
}
