//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ControlStyle
    {
        [Key]
        public System.Guid DocumentContentId { get; set; }
        public System.Guid FontID { get; set; }
        public byte FontSize { get; set; }
        public string? FontColor { get; set; }
        public bool IsBold { get; set; }
        public bool IsItalic { get; set; }
        public bool IsUnderline { get; set; }
        public string? AdditionalValidationName { get; set; }
        public string? AdditionalValidationOption { get; set; }  
    }
}
