//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUploadedFiles
    {
        public int DocumentId { get; set; }
        public string? FileName { get; set; }
        public string? SizeInKbs { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string? CompanyUserLevel { get; set; }
    }
}
