//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDetail
    {
        public int ContactId { get; set; }
        public string? JobTitle { get; set; }
        public string? Company { get; set; }
        public string? Name { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string? EmailID { get; set; }
        public System.Guid CompanyId { get; set; }
        public string? CompanyUserLevel { get; set; }
        public int DocumentId { get; set; }
        public string? CreatedSource { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public System.Guid CreatedUserId { get; set; }
        public System.Guid ModifiedUserId { get; set; }
        public string CountryCode { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsReadOnly { get; set; }
        public string DialCode { get; set; }
        public string CountryName { get; set; }
    }
}
