//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelegatedControls
    {
        public long TransId { get; set; }
        public Nullable<System.Guid> DelegatedRecipientID { get; set; }
        public string? DelegatedEmailAddress { get; set; }
        public Nullable<System.Guid> OriginalRecipientID { get; set; }
        public Nullable<System.Guid> ParentRecipientID { get; set; }
        public Nullable<System.Guid> ControlID { get; set; }
        public string? ControlValue { get; set; }
        public string? OriginalControlValue { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    }
}
