//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DeletedEnvelopeFolderHistory
    {
        [Key]
        public long TransId { get; set; }
        public System.Guid EnvelopeId { get; set; }
        public System.Guid UserID { get; set; }
        public string? SettingText { get; set; }
        public int RetentionDays { get; set; }
        public bool OptionValue { get; set; }
        public System.DateTime DeletedDatetime { get; set; }
        public string? EnvelopeCode { get; set; }
    }
}
