//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Destination
    {
        [Key]
        public long TransId { get; set; }
        public string? EnvelopeCode { get; set; }
        public string? RecipientEmail { get; set; }
        public bool IsSent { get; set; }
        public Nullable<short> DeliveryStatus { get; set; }
        public string? DeliveryStatusDetail { get; set; }
        public bool IsProcessed { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public Nullable<System.Guid> MessageId { get; set; }
        public Nullable<bool> IsNotifiedSender { get; set; }
        public string? EmailSentType { get; set; }
        public Nullable<int> RetryCount { get; set; }
    }
}
