//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentSizeLanguageMapping
    {
        public long TransID { get; set; }
        public Nullable<long> DocumentKeyID { get; set; }

       #nullable enable  
        public string? LanguageID { get; set; }
       #nullable enable 
        public string? Description { get; set; }
    }
}
