//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentConversionLog
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> EnvelopeID { get; set; }
        public string? DocumentName { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string? Remarks { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    }
}
