//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DocumentsTransaction
    {
        public int ID { get; set; }     
       // public System.Guid DocumentID { get; set; }
        public System.Guid EnvelopeID { get; set; }
#nullable enable
        public string? DocumentName { get; set; }
        public System.DateTime UploadedDateTime { get; set; }
#nullable enable
        public string? SourceLocation { get; set; }
        public Nullable<int> NoOfTimesTried { get; set; }
        public Nullable<bool> EmailSentToSender { get; set; }
        public Nullable<bool> IsDocumentUploaded { get; set; }
    }
}
