//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropdownOptions
    {
        public int ID { get; set; }
        public int ParentID { get; set; }
#nullable enable
        public string? FieldName { get; set; }
        public Nullable<System.Guid> LanguageID { get; set; }
#nullable enable
        public string? OptionName { get; set; }
#nullable enable
        public string? OptionValue { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
    }
}
