//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DsnLog
    {
        public long TransID { get; set; }
#nullable enable
        public string? MessageId { get; set; }
#nullable enable
        public string? ActionValue { get; set; }
#nullable enable
        public string? StatusValue { get; set; }
#nullable enable
        public string? ContentType { get; set; }
#nullable enable
        public string? DeliveryStatus { get; set; }
#nullable enable
        public string? DeliveryReport { get; set; }
#nullable enable
        public string? DeliveryStatusRegexMatch { get; set; }
#nullable enable
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
    }
}
