//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailQueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailQueue()
        {
            this.EmailQueueRecipients = new HashSet<EmailQueueRecipients>();
        }
    
        public int ID { get; set; }
        public Nullable<System.Guid> EnvelopeId { get; set; }
        public string? EmailType { get; set; }
        public Nullable<int> Status { get; set; }
        public string? Message { get; set; }
        public string? Subject { get; set; }
        public string? Body { get; set; }
        public string? EnvelopeCode { get; set; }
        public string? SenderName { get; set; }
        public string? SenderEmail { get; set; }
        public Nullable<int> SignReqReplyToAddressValue { get; set; }
        public Nullable<bool> isAttachment { get; set; }
        public Nullable<int> ReprocessCount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string? CreatedServer { get; set; }
        public string? ProcessedServer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailQueueRecipients> EmailQueueRecipients { get; set; }
    }
}
