//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailQueueRecipients
    {
        public int ID { get; set; }
        public int EmailQueueId { get; set; }
        public Nullable<System.Guid> EnvelopeId { get; set; }
        public string? EmailType { get; set; }
        public string? RecipientEmail { get; set; }
        public string? RecipientName { get; set; }
        public string? Subject { get; set; }
        public string? Body { get; set; }
        public Nullable<int> Status { get; set; }
        public string? Message { get; set; }
        public Nullable<int> ReprocessCount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string? Server { get; set; }
    
        public virtual EmailQueue EmailQueue { get; set; }
    }
}
