//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmailLogs
    {
        [Key]
        public int LogId { get; set; }
        public string? MessageId { get; set; }
        public string? EnvelopeCode { get; set; }
        public string? ResponseMessage { get; set; }
        public string? InnerException { get; set; }
        public string? FullException { get; set; }
        public string? ServerName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
