//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvelopeTemplateGroups
    {
        public System.Guid ID { get; set; }
        public System.Guid MasterEnvelopeID { get; set; }
        public System.Guid UserID { get; set; }
        public string? Subject { get; set; }
        public string? Message { get; set; }
        public string? TemplateName { get; set; }
        public string? TemplateDescription { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.Guid TemplateID { get; set; }
        public Nullable<int> Order { get; set; }
        public bool IsSequenceCheck { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public Nullable<bool> IsDraft { get; set; }
        public string? EnvelopeCode { get; set; }
    }
}
