//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvelopeSettingsDetail
    {
        public int Id { get; set; }
        public System.Guid EnvelopeId { get; set; }
        public Nullable<bool> DeleteOriginalDocument { get; set; }
        public Nullable<int> FinalContractOptions { get; set; }
        public Nullable<System.Guid> AttachSignedPdf { get; set; }
        public Nullable<bool> IsDeleteSignedContracts { get; set; }
        public Nullable<int> ReferenceCode { get; set; }
        public Nullable<bool> StoreEmailBody { get; set; }
        public Nullable<bool> AllowUserToDelete { get; set; }
        public Nullable<bool> ReceiveSendingConfirmation { get; set; }
        public Nullable<bool> DocumentsCombinedInOneEnvelope { get; set; }
        public Nullable<int> SendInvitationEmailToSigner { get; set; }
        public Nullable<int> CertificatePaperSize { get; set; }
        public Nullable<int> SignReqReplyAdrs { get; set; }
        public Nullable<bool> AllowAlignField { get; set; }
        public Nullable<bool> SignatureControlRequired { get; set; }
        public Nullable<bool> SignatureCaptureType { get; set; }
        public Nullable<bool> SignatureCaptureHandDrawn { get; set; }
        public string? TimeZone { get; set; }
        public Nullable<bool> IsEnableDependencies { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<bool> IsEnableClickToSign { get; set; }
        public Nullable<bool> UploadSignature { get; set; }
        public Nullable<int> DigitalCertificate { get; set; }
        public string? AppKey { get; set; }
        public string? AppliedEpicUser { get; set; }
        public string? AppliedEpicEntityId { get; set; }
        public string? IntegrationType { get; set; }
        public string? EntityType { get; set; }
        public string? PostSendingNavigationPage { get; set; }
    }
}
