//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EnvelopeTemplateMapping
    {
        [Key]
        public int MappingId { get; set; }
        public System.Guid EnvelopeId { get; set; }
        public System.Guid TemplateId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> TemplateCode { get; set; }
        public string? TemplateName { get; set; }
        public Nullable<System.Guid> EnvelopeTypeId { get; set; }
    }
}
