//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EnvelopeDocumentDeleteData
    {
        [Key]
        public int Id { get; set; }
        public System.Guid EnvelopeId { get; set; }
        public Nullable<System.Guid> DocumentId { get; set; }
        public string? DocumentType { get; set; }
        public string? DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    }
}
