//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvelopeHistory
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public Nullable<int> EnvelopeCode { get; set; }
        public System.Guid DateFormatID { get; set; }
        public System.Guid ExpiryTypeID { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<int> ReminderDays { get; set; }
        public Nullable<int> ReminderRepeatDays { get; set; }
        public bool PasswordReqdtoSign { get; set; }
        public string? PasswordtoSign { get; set; }
        public bool PasswordReqdtoOpen { get; set; }
        public string? PasswordtoOpen { get; set; }
        public string? SigningCertificateName { get; set; }
        public System.Guid StatusID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public string? Subject { get; set; }
        public string? Message { get; set; }
        public string? Location { get; set; }
        public Nullable<int> PasswordKeySize { get; set; }
        public string? PasswordKey { get; set; }
        public string? DocumentHash { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> TemplateCode { get; set; }
        public bool IsEnvelope { get; set; }
        public string? TemplateName { get; set; }
        public string? TemplateDescription { get; set; }
        public bool IsTemplateDeleted { get; set; }
        public bool IsTemplateEditable { get; set; }
        public int DisplayCode { get; set; }
        public Nullable<bool> IsDraft { get; set; }
        public Nullable<bool> IsDraftSend { get; set; }
        public Nullable<bool> IsDraftDeleted { get; set; }
        public string? CultureInfo { get; set; }
        public Nullable<bool> IsFinalCertificateReq { get; set; }
        public Nullable<bool> IsFinalDocLinkReq { get; set; }
        public Nullable<bool> IsEnvelopePrepare { get; set; }
        public bool IsEnvelopeComplete { get; set; }
        public bool IsSequenceCheck { get; set; }
        public bool IsTemplateShared { get; set; }
        public bool IsTransparencyDocReq { get; set; }
        public string? EnvelopJson { get; set; }
        public bool IsDisclaimerAccepted { get; set; }
        public string? DisclaimerText { get; set; }
        public bool IsFinalContractDeleted { get; set; }
        public Nullable<System.Guid> EnvelopeTypeId { get; set; }
        public bool IsSharedTemplateContentUnEditable { get; set; }
        public Nullable<System.Guid> SharedTemplateID { get; set; }
        public Nullable<int> IsSignerAttachFileReq { get; set; }
        public Nullable<bool> IsStatic { get; set; }
        public Nullable<bool> IsAttachXML { get; set; }
        public bool IsSeparateMultipleDocumentsAfterSigningRequired { get; set; }
        public string? EDisplayCode { get; set; }
        public Nullable<bool> IsDisclaimerInCertificate { get; set; }
        public Nullable<System.Guid> TemplateKey { get; set; }
        public Nullable<System.Guid> AccessAuthType { get; set; }
        public bool IsPasswordMailToSigner { get; set; }
        public bool IsRandomPassword { get; set; }
        public bool IsEmailBodyDisplay { get; set; }
        public Nullable<System.Guid> LanguageID { get; set; }
        public Nullable<bool> IsEdited { get; set; }
        public Nullable<int> HeaderFooterOption { get; set; }
        public string? PostSigningLandingPage { get; set; }
        public Nullable<System.Guid> ReminderTypeID { get; set; }
        public Nullable<System.Guid> ThenReminderTypeID { get; set; }
        public Nullable<System.Guid> UserSignatureTextID { get; set; }
        public Nullable<System.Guid> MessageTemplateTextID { get; set; }
        public Nullable<bool> SendIndividualSignatureNotifications { get; set; }
        public Nullable<int> FinalReminderDays { get; set; }
        public Nullable<System.Guid> FinalReminderTypeID { get; set; }
        public Nullable<bool> IsDefaultSignatureForStaticTemplate { get; set; }
        public Nullable<long> TemplateGroupId { get; set; }
        public Nullable<int> ElectronicSignIndicationOptionID { get; set; }
        public Nullable<bool> IsWaterMark { get; set; }
        public string? WatermarkTextForSender { get; set; }
        public string? WatermarkTextForOther { get; set; }
        public string? ReferenceCode { get; set; }
        public string? ReferenceEmail { get; set; }
        public Nullable<bool> IsPrivateMode { get; set; }
        public Nullable<bool> IsSignatureCertificateStored { get; set; }
        public Nullable<bool> IsStoreOriginalDocument { get; set; }
        public Nullable<bool> IsStoreSignatureCertificate { get; set; }
        public Nullable<bool> IsRule { get; set; }
        public Nullable<bool> IsAdditionalAttmReq { get; set; }
        public Nullable<bool> IsEnableFileReview { get; set; }
        public Nullable<bool> IsEnableAutoFillTextControls { get; set; }
        public Nullable<bool> IsSignerIdentitiy { get; set; }
        public string? CreatedSource { get; set; }
        public Nullable<System.Guid> CopyEnvelopeId { get; set; }
        public string? DraftType { get; set; }
        public Nullable<bool> AllowMultiSigner { get; set; }
        public string? EnvelopeExpirationRemindertoSender { get; set; }
        public string? SendReminderTillExpiration { get; set; }
        public Nullable<int> EnvelopeExpirationRemindertoSenderReminderDays { get; set; }
        public Nullable<int> IsEnvelopeExpirationRemindertoSender { get; set; }
        public Nullable<int> ISSendReminderTillExpiration { get; set; }
        public string? InviteMessage { get; set; }
        public Nullable<bool> IsInvitedBySigner { get; set; }
        public Nullable<bool> SendConfirmationEmail { get; set; }
        public Nullable<bool> ISNewSigner { get; set; }
        public Nullable<bool> EnableCcOptions { get; set; }
        public Nullable<bool> IsSameRecipientForAllTemplates { get; set; }
        public Nullable<bool> EnableRecipientLanguage { get; set; }
        public Nullable<bool> EnableMessageToMobile { get; set; }
        public Nullable<bool> RestrictRecipientsToContact { get; set; }
        public Nullable<bool> ReVerifySignerDocumentSubmit { get; set; }
        public Nullable<bool> IsSendMessageCodetoAvailableEmailorMobile { get; set; }
    }
}
