//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Language()
        {
            this.Company = new HashSet<Company>();
            this.UserProfile = new HashSet<UserProfile>();
            this.LanguageKeyDetails = new HashSet<LanguageKeyDetails>();
            this.Envelope = new HashSet<Envelope>();
            this.AttachSignedPdfLanguageMapping = new HashSet<AttachSignedPdfLanguageMapping>();
            this.SettingsAccessLanguageMapping = new HashSet<SettingsAccessLanguageMapping>();
            this.UserTypeLanguageMapping = new HashSet<UserTypeLanguageMapping>();
            this.SettingsDisplayLanguageMapping = new HashSet<SettingsDisplayLanguageMapping>();
        }
    
        public System.Guid ID { get; set; }
        public string? LanguageCode { get; set; }
        public string? Description { get; set; }
        public bool IsEnable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LanguageKeyDetails> LanguageKeyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Envelope> Envelope { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachSignedPdfLanguageMapping> AttachSignedPdfLanguageMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SettingsAccessLanguageMapping> SettingsAccessLanguageMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTypeLanguageMapping> UserTypeLanguageMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SettingsDisplayLanguageMapping> SettingsDisplayLanguageMapping { get; set; }
    }
}
