//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageKeyTranslation
    {
        public System.Guid Id { get; set; }
        public string? KeyTranslation { get; set; }
        public string? Comments { get; set; }
        public string? Status { get; set; }
        public string? PageName { get; set; }
        public System.Guid Created_By { get; set; }
        public System.DateTime Created_On { get; set; }
    }
}
