//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageKeyDetails
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ResourceKeyID { get; set; }
        public Nullable<System.Guid> LanguageID { get; set; }
        public string? KeyValue { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual ResourceKey ResourceKey { get; set; }
    }
}
