//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailTemplateNew
    {
        public System.Guid ID { get; set; }
        public string? Name { get; set; }
        public string? Template { get; set; }
        public string? CultureInfo { get; set; }
        public string? MobileTemplate { get; set; }
    }
}
