//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTemplate
    {
        public System.Guid ID { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        public string? Subject { get; set; }
        public string? EmailBody { get; set; }
        public bool IsShared { get; set; }
        public Nullable<System.Guid> SharedId { get; set; }
        public System.Guid UserID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> TemplateCode { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.Guid> UserSignatureTextID { get; set; }
    }
}
