//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonRpostUser
    {
        public System.Guid ID { get; set; }
        public string? Name { get; set; }
        public string? EmailAddress { get; set; }
        public string? Title { get; set; }
        public string? Company { get; set; }
        public byte[] Signature { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string? Initials { get; set; }
        public string? SignatureText { get; set; }
        public string? FontClass { get; set; }
        public System.Guid SignatureTypeID { get; set; }
    }
}
