//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RAppNotificationEvents
    {
        [Key]
        public int EnvelopeEventId { get; set; }
        public string? NotificationTypeCode { get; set; }
        public System.Guid UserId { get; set; }
        public string? UserEmail { get; set; }
        public int ExpiryDays { get; set; }
        public System.Guid EnvelopeId { get; set; }
        public System.Guid EnvelopeStatusId { get; set; }
        public System.Guid RecipientId { get; set; }
        public System.Guid SignerStatusId { get; set; }
        public bool IsRead { get; set; }
        public bool IsExpired { get; set; }
        public string? SenderEmail { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public string? EDisplayCode { get; set; }
        public string? DelegatedMessage { get; set; }
        public Nullable<bool> IsNotified { get; set; }
    }
}
