//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipientsDetailHistory
    {
        public System.Guid ID { get; set; }
        public System.Guid RecipientID { get; set; }
        public System.Guid StatusTypeID { get; set; }
        public System.DateTime StatusDateTime { get; set; }
        public string? IPAddress { get; set; }
        public string? OldRecipient { get; set; }
        public string? OldEmail { get; set; }
        public string? CurrentRecipient { get; set; }
        public string? CurrentEmail { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public string? SignedBy { get; set; }
        public string DialCode { get; set; }
        public string CountryCode { get; set; }
        public string Mobile { get; set; }
        public string OldDialCode { get; set; }
        public string OldCountryCode { get; set; }
        public string OldMobile { get; set; }
    }
}
