//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Recipients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipients()
        {
           // this.SignerSignature = new HashSet<SignerSignature>();
            this.SignerStatus = new HashSet<SignerStatus>();
            this.RecipientsDetail = new HashSet<RecipientsDetail>();
        }

        public System.Guid ID { get; set; }
        public System.Guid EnvelopeID { get; set; }
        public System.Guid RecipientTypeID { get; set; }
        public string? Name { get; set; }
        public string? EmailAddress { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string? RerouteEmailAddress { get; set; }
        public Nullable<System.Guid> TemplateID { get; set; }
        public string? RecipientCode { get; set; }
        public Nullable<long> TemplateGroupId { get; set; }
        public Nullable<System.Guid> EnvelopeTemplateGroupID { get; set; }
        public Nullable<System.Guid> TemplateRoleId { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public Nullable<int> EmailDeliveryStatus { get; set; }
        public string? CopyEmailAddress { get; set; }
        public Nullable<int> IsReviewed { get; set; }
        public string? Comments { get; set; }
        public bool IsSameRecipient { get; set; }
        public string? VerificationCode { get; set; }
        public Nullable<int> SignNowOrInviteEmail { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<int> CCSignerType { get; set; }
        public string? CultureInfo { get; set; }
        public Nullable<int> DeliveryMode { get; set; }
        public string? DialCode { get; set; }
        public string? CountryCode { get; set; }
        public string? Mobile { get; set; }
       // public Nullable<int> ReminderType { get; set; }
        public Nullable<bool> IsReadonlyContact { get; set; }
        public Nullable<bool> SendDocumentOnDelegate { get; set; }
        public virtual Envelope Envelope { get; set; }
        public virtual RecipientType RecipientType { get; set; }
        
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<SignerSignature> SignerSignature { get; set; }
       
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [NotMapped]
        public virtual ICollection<SignerStatus> SignerStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipientsDetail> RecipientsDetail { get; set; }
    }
}
