//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSignAPIPayload
    {
        public int PayloadId { get; set; }
        public string? PayloadType { get; set; }
        public string? PayloadTypeId { get; set; }
        public string? APIMethod { get; set; }
        public string? UserEmail { get; set; }
        public string? PayloadInfo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string? ServerName { get; set; }
    }
}
