//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleConfig
    {
        public System.Guid ID { get; set; }
        public string? RuleText { get; set; }
        public System.Guid RuleFor { get; set; }
        public string? RuleDescription { get; set; }
        public Nullable<byte> DisplayOrder { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Control Control { get; set; }
    }
}
