//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleConfLanguageMapping
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> MasterReferenceKeyID { get; set; }
        public Nullable<System.Guid> LanguageID { get; set; }
        public Nullable<System.Guid> RuleTextFor { get; set; }
        public string? RuleText { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
