//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class SelectControlOptions
    {       
        public System.Guid ID { get; set; }
        public System.Guid DocumentContentID { get; set; }
        public string? OptionText { get; set; }
        public byte Order { get; set; }
        [NotMapped]
        public DocumentContents DocumentContents { get; set; }
    }
}
