//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SettingsDetail
    {
        public System.Guid ID { get; set; }
        public System.Guid KeyConfig { get; set; }
        public int OptionFlag { get; set; }
        public string? OptionValue { get; set; }
        public System.Guid SettingsFor { get; set; }
        public string? SettingsForType { get; set; }
        public System.Guid UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<bool> IsOverride { get; set; }
        public Nullable<bool> IsLock { get; set; }

        [NotMapped]
        public virtual SettingsKeyConfig SettingsKeyConfig { get; set; }
    }
}
