//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsKeyConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SettingsKeyConfig()
        {
            this.SettingsDetail = new HashSet<SettingsDetail>();
        }
    
        public System.Guid ID { get; set; }
        public string? KeyText { get; set; }
        public string? Description { get; set; }
        public Nullable<bool> DefaultFlag { get; set; }
        public string? DefaultValue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SettingsDetail> SettingsDetail { get; set; }
    }
}
