//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsDisplayLanguageMapping
    {
        public System.Guid ID { get; set; }
        public Nullable<int> MasterReferenceKeyID { get; set; }
        public Nullable<System.Guid> LanguageID { get; set; }
        public string? DescriptionValue { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual SettingsDisplayLanguageMapping SettingsDisplayLanguageMapping1 { get; set; }
        public virtual SettingsDisplayLanguageMapping SettingsDisplayLanguageMapping2 { get; set; }
        public virtual SettingsDisplayOptions SettingsDisplayOptions { get; set; }
    }
}
