//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsExternalIntegration
    {
        public Nullable<System.Guid> UserID { get; set; }
        public string? UserEmailId { get; set; }
        public Nullable<decimal> CustomerId { get; set; }
        public string? AccessToken { get; set; }
        public string? RefreshToken { get; set; }
        public Nullable<System.DateTime> RefreshTokenUpdatedOn { get; set; }
        public Nullable<System.DateTime> RefreshTokenExpiredOn { get; set; }
        public string? SignedDocumentsFolder { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string? IsUploadSignedDocument { get; set; }
        public System.Guid ID { get; set; }
        public string? DocumentPath { get; set; }
        public string? IntegrationType { get; set; }
        public string? UserName { get; set; }
        public string? SignedDocumentsFolderId { get; set; }
        public string? SignedDocumentsWorkSpaceId { get; set; }
        public string? Platform { get; set; }
        public string? Version { get; set; }
        public string? ServerURL { get; set; }
        public string? CustomerUserId { get; set; }
        public Nullable<System.Guid> Settinggsfor { get; set; }
        public string? SettingsType { get; set; }
        public string? Region { get; set; }
        public string? ApplicationURL { get; set; }
        public string? ApplicationAPIURL { get; set; }
        public string? AppClientId { get; set; }
        public string? AppClientSecret { get; set; }
        public string? RedirectURI { get; set; }
        public string? DefaultRepository { get; set; }
        public Nullable<int> FilingFinalSignedDocuments { get; set; }
        public string? CheckOutComment { get; set; }
        public string? CheckInComment { get; set; }
        public string? SigningProcessCompleteComment { get; set; }
        public string? FinalSignedDocumentNameFormat { get; set; }
        public string? SignatureCertificateNameFormat { get; set; }
        public Nullable<int> FilingFinalSignedDocumentOptions { get; set; }
    }
}
