//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SignerStatus
    {
        public System.Guid ID { get; set; }       
        public System.Guid RecipientID { get; set; }
        public System.Guid StatusID { get; set; }
        public string? RejectionRemarks { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string? IPAddress { get; set; }
        public Nullable<System.Guid> DelegateTo { get; set; }
        public Nullable<int> DeclineReasonID { get; set; }
        public string? SignedBy { get; set; }
        //[NotMapped]
        //public virtual Status Status { get; set; }
        //[NotMapped]
        //public virtual Recipients Recipients { get; set; }
    }
}
