//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignerSignature
    {
        public System.Guid ID { get; set; }
        public System.Guid RecipientID { get; set; }
        public System.Guid SignatureTypeId { get; set; }
        public byte[] Signature { get; set; }  
        
        //public virtual Recipients Recipients { get; set; }
    }
}
