//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateGroups()
        {
            this.TemplateGroupContents = new HashSet<TemplateGroupContents>();
            this.TemplateGroupDocumentUpload = new HashSet<TemplateGroupDocumentUpload>();
        }
    
        public long ID { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid DateFormatID { get; set; }
        public System.Guid ExpiryTypeID { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<int> ReminderDays { get; set; }
        public Nullable<int> ReminderRepeatDays { get; set; }
        public bool PasswordReqdtoSign { get; set; }
        public string? PasswordtoSign { get; set; }
        public bool PasswordReqdtoOpen { get; set; }
        public string? PasswordtoOpen { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public string? Subject { get; set; }
        public string? Message { get; set; }
        public Nullable<int> PasswordKeySize { get; set; }
        public string? PasswordKey { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string? GroupName { get; set; }
        public string? GroupDescription { get; set; }
        public string? CultureInfo { get; set; }
        public Nullable<bool> IsFinalCertificateReq { get; set; }
        public Nullable<bool> IsFinalDocLinkReq { get; set; }
        public Nullable<bool> IsTransparencyDocReq { get; set; }
        public Nullable<int> IsSignerAttachFileReq { get; set; }
        public Nullable<bool> IsAttachXML { get; set; }
        public Nullable<bool> IsSeparateMultipleDocumentsAfterSigningRequired { get; set; }
        public Nullable<System.Guid> TemplateKey { get; set; }
        public Nullable<System.Guid> AccessAuthType { get; set; }
        public bool IsPasswordMailToSigner { get; set; }
        public bool IsRandomPassword { get; set; }
        public string? PostSigningLandingPage { get; set; }
        public Nullable<System.Guid> ReminderTypeID { get; set; }
        public Nullable<System.Guid> UserSignatureTextID { get; set; }
        public Nullable<System.Guid> ThenReminderTypeID { get; set; }
        public Nullable<System.Guid> MessageTemplateTextID { get; set; }
        public Nullable<bool> SendIndividualSignatureNotifications { get; set; }
        public Nullable<int> FinalReminderDays { get; set; }
        public Nullable<System.Guid> FinalReminderTypeID { get; set; }
        public Nullable<System.DateTime> LastAccessedDateTime { get; set; }
        public bool IsSequenceCheck { get; set; }
        public Nullable<bool> IsPrivateMode { get; set; }
        public Nullable<bool> IsStoreOriginalDocument { get; set; }
        public Nullable<bool> IsStoreSignatureCertificate { get; set; }
        public Nullable<bool> IsSignerIdentity { get; set; }
        public string? EnvelopeExpirationRemindertoSender { get; set; }
        public string? SendReminderTillExpiration { get; set; }
        public Nullable<int> IsEnvelopeExpirationRemindertoSender { get; set; }
        public Nullable<int> ISSendReminderTillExpiration { get; set; }
        public Nullable<int> EnvelopeExpirationRemindertoSenderReminderDays { get; set; }
        public Nullable<bool> EnableCcOptions { get; set; }
        public Nullable<bool> EnableRecipientLanguage { get; set; }
    
        public virtual DateFormat DateFormat { get; set; }
        public virtual ExpiryType ExpiryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateGroupContents> TemplateGroupContents { get; set; }
        public virtual TemplateGroups TemplateGroups1 { get; set; }
        public virtual TemplateGroups TemplateGroups2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateGroupDocumentUpload> TemplateGroupDocumentUpload { get; set; }
    }
}
