//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateGroupDocumentUpload
    {
        public long ID { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        public string? AdditionalInfo { get; set; }
        public bool IsRequired { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<long> TemplateGroupId { get; set; }
        public string? FileName { get; set; }
        public Nullable<System.Guid> TemplateId { get; set; }
        public Nullable<System.Guid> RecipientID { get; set; }
        public string? RecipientEmailID { get; set; }
    
        public virtual TemplateGroups TemplateGroups { get; set; }
    }
}
