//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateGroupContents
    {
        public long ID { get; set; }
        public long TemplateGroupId { get; set; }
        public Nullable<System.Guid> TemplateID { get; set; }
        public Nullable<System.Guid> RuleID { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual TemplateGroups TemplateGroups { get; set; }
    }
}
