//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Template()
        {
            this.TemplateDocuments = new HashSet<TemplateDocuments>();
            this.TemplateRoles = new HashSet<TemplateRoles>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid DateFormatID { get; set; }
        public System.Guid ExpiryTypeID { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<int> ReminderDays { get; set; }
        public Nullable<int> ReminderRepeatDays { get; set; }
        public bool PasswordReqdtoSign { get; set; }
        public string? PasswordtoSign { get; set; }
        public bool PasswordReqdtoOpen { get; set; }
        public string? PasswordtoOpen { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public string? Subject { get; set; }
        public string? Message { get; set; }
        public Nullable<int> PasswordKeySize { get; set; }
        public string? PasswordKey { get; set; }
        public bool IsSequenceCheck { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> TemplateCode { get; set; }
        public string? TemplateName { get; set; }
        public string? TemplateDescription { get; set; }
        public bool IsTemplateEditable { get; set; }
        public string? CultureInfo { get; set; }
        public Nullable<bool> IsTemplatePrepare { get; set; }
        public Nullable<int> IsTemplateShared { get; set; }
        public Nullable<bool> IsFinalCertificateReq { get; set; }
        public Nullable<bool> IsFinalDocLinkReq { get; set; }
        public Nullable<bool> IsTransparencyDocReq { get; set; }
        public Nullable<int> IsSignerAttachFileReq { get; set; }
        public Nullable<bool> IsAttachXML { get; set; }
        public Nullable<bool> IsSeparateMultipleDocumentsAfterSigningRequired { get; set; }
        public string? TemplateJson { get; set; }
        public Nullable<System.Guid> EnvelopeTypeId { get; set; }
        public Nullable<System.Guid> SharedTemplateID { get; set; }
        public Nullable<bool> IsStatic { get; set; }
        public string? EDisplayCode { get; set; }
        public Nullable<System.Guid> TemplateKey { get; set; }
        public Nullable<System.Guid> AccessAuthType { get; set; }
        public bool IsPasswordMailToSigner { get; set; }
        public bool IsRandomPassword { get; set; }
        public bool IsSharedTemplateContentUnEditable { get; set; }
        public bool IsTemplateCompleted { get; set; }
        public string? PostSigningLandingPage { get; set; }
        public Nullable<System.Guid> ReminderTypeID { get; set; }
        public Nullable<System.Guid> ThenReminderTypeID { get; set; }
        public Nullable<System.Guid> UserSignatureTextID { get; set; }
        public Nullable<System.Guid> MessageTemplateTextID { get; set; }
        public Nullable<bool> SendIndividualSignatureNotifications { get; set; }
        public Nullable<int> FinalReminderDays { get; set; }
        public Nullable<System.Guid> FinalReminderTypeID { get; set; }
        public Nullable<System.DateTime> LastAccessedDateTime { get; set; }
        public Nullable<bool> IsDefaultSignatureForStaticTemplate { get; set; }
        public string? ReferenceCode { get; set; }
        public string? ReferenceEmail { get; set; }
        public Nullable<bool> IsPrivateMode { get; set; }
        public Nullable<bool> IsStoreOriginalDocument { get; set; }
        public Nullable<bool> IsStoreSignatureCertificate { get; set; }
        public Nullable<bool> IsStaticLinkDisabled { get; set; }
        public Nullable<bool> IsEnableFileReview { get; set; }
        public Nullable<bool> IsRuleEditable { get; set; }
        public Nullable<bool> IsAdditionalAttmReq { get; set; }
        public Nullable<bool> IsEnableAutoFillTextControls { get; set; }
        public Nullable<bool> IsSignerIdentitiy { get; set; }
        public Nullable<bool> AllowMultiSigner { get; set; }
        public string? EnvelopeExpirationRemindertoSender { get; set; }
        public string? SendReminderTillExpiration { get; set; }
        public Nullable<int> IsEnvelopeExpirationRemindertoSender { get; set; }
        public Nullable<int> ISSendReminderTillExpiration { get; set; }
        public Nullable<int> EnvelopeExpirationRemindertoSenderReminderDays { get; set; }
        public Nullable<bool> SendConfirmationEmail { get; set; }
        public Nullable<bool> EnableCcOptions { get; set; }
        public Nullable<bool> EnableRecipientLanguage { get; set; }
        public string IntegrationType { get; set; }
        public string IntegrationUser { get; set; }
        public string EntityId { get; set; }
        public string EntityType { get; set; }
        public Nullable<bool> EnableMessageToMobile { get; set; }   
        public Nullable<bool> RestrictRecipientsToContact { get; set; }  
        public Nullable<bool> ReVerifySignerStaticTemplate { get; set; }
        public Nullable<System.DateTime> StaticLinkExpiryDate { get; set; }

        public virtual DateFormat DateFormat { get; set; }
        public virtual ExpiryType ExpiryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateDocuments> TemplateDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateRoles> TemplateRoles { get; set; }
    }
}
