//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TemplateDocumentContents
    {    
        public System.Guid ID { get; set; }
        public System.Guid ControlID { get; set; } 
        public System.Guid DocumentID { get; set; }
        public Nullable<System.Guid> RecipientID { get; set; }
        public string? ControlHtmlID { get; set; }
        public bool Required { get; set; }
        public Nullable<int> DocumentPageNo { get; set; }
        public Nullable<int> PageNo { get; set; }
        public Nullable<int> XCoordinate { get; set; }
        public Nullable<int> YCoordinate { get; set; }
        public Nullable<int> ZCoordinate { get; set; }
        public string? ControlValue { get; set; }
        public string? Label { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public string? GroupName { get; set; }
        public string? ControlHtmlData { get; set; }
        public string? RecName { get; set; }
        public bool IsControlDeleted { get; set; }
        public Nullable<System.Guid> MaxLength { get; set; }
        public Nullable<System.Guid> ControlType { get; set; }
        public Nullable<double> LeftIndex { get; set; }
        public Nullable<double> TopIndex { get; set; }
        public string? SenderControlValue { get; set; }
        public byte[] SignatureControlValue { get; set; }
        public Nullable<int> TabIndex { get; set; }
        public string? IntControlId { get; set; }
        public string? OrignalPageFormat { get; set; }
        public string? Size { get; set; }
        public Nullable<bool> IsDefaultRequired { get; set; }
        public string? CustomToolTip { get; set; }
        public string? FontTypeMeasurement { get; set; }
        public Nullable<bool> IsFixedWidth { get; set; }

        //public virtual Control Control { get; set; }    
        //public virtual TemplateControlStyle TemplateControlStyle { get; set; }   
        //public virtual TemplateDocuments TemplateDocuments { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<TemplateSelectControlOptions> TemplateSelectControlOptions { get; set; }
    }
}
