//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateRoles
    {
        public System.Guid ID { get; set; }
        public System.Guid TemplateID { get; set; }
        public string? Name { get; set; }
        public Nullable<int> Order { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.Guid RecipientTypeID { get; set; }
        public string? Description { get; set; }
        public Nullable<int> CCSignerType { get; set; }
        public string? CultureInfo { get; set; }
        public Nullable<int> DeliveryMode { get; set; }
        public string CountryCode { get; set; }
        public string DialCode { get; set; }
     //   public Nullable<int> ReminderType { get; set; }
        public virtual RecipientType RecipientType { get; set; }
        public virtual Template Template { get; set; }
    }
}
