//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TextType()
        {
            //this.DocumentContents = new HashSet<DocumentContents>();
            //this.TemplateDocumentContents = new HashSet<TemplateDocumentContents>();
        }
    
        public System.Guid ID { get; set; }
        public string? Type { get; set; }
        public string? CultureInfo { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public Nullable<int> Order { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DocumentContents> DocumentContents { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<TemplateDocumentContents> TemplateDocumentContents { get; set; }
    }
}
