//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public string? Title { get; set; }
        public string? Initials { get; set; }
        public string? Company { get; set; }
        public byte[] Photo { get; set; }
        public string? SignatureText { get; set; }
        public string? FontClass { get; set; }
        public System.Guid SignatureTypeID { get; set; }
        public byte[] SignatureImage { get; set; }
        public string? FirstName { get; set; }     
        public string? LastName { get; set; }
        public string? EmailID { get; set; }
        public Nullable<System.Guid> UserTypeID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public bool IsActive { get; set; }
        public bool IsUserApproved { get; set; }
        public string? MessageSignatureText { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<bool> IsReview { get; set; }
        public Nullable<System.Guid> status { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public Nullable<System.Guid> LanguageID { get; set; }
        public string? LanguageCode { get; set; }
        public bool IsAutoPopulateSignaturewhileSinging { get; set; }
        public string? ExternalIdentityProvider { get; set; }
    
        public Company Company1 { get; set; }
        public Language Language { get; set; }
        public UserType UserType { get; set; }
    }
}
