//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToken
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public string? EmailId { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime ExpiresIn { get; set; }
        public string? AuthToken { get; set; }
        public string? BrowserName { get; set; }
        public string? IPAddress { get; set; }
        public string? ReferenceKey { get; set; }
        public string? RefreshToken { get; set; }
        public Nullable<System.DateTime> RefreshTokenExpiresOn { get; set; }
        public string? TokenType { get; set; }
        public bool IsReseller { get; set; }
    }
}
