//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSign.Models.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserPlan
    {
        [Key]
        public System.Guid UserId { get; set; }
        public string? PlanCode { get; set; }       
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string? PlanType { get; set; }
        public Nullable<bool> IsTrailPlan { get; set; }
        public Nullable<bool> IsDefaultPlan { get; set; }
        public Nullable<bool> IsPaidPlan { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
