//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSignatureText
    {
        public System.Guid ID { get; set; }
        public System.Guid UserId { get; set; }
        public string? SignatureName { get; set; }
        public string? SignatureText { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public bool IsDefault { get; set; }
        public bool IsDeleted { get; set; }
    }
}
